# vim: set filetype=ansible
# vim: set filetype=yaml.ansible :
---
- name: Generate files | Generate terraform pmx main files
  delegate_to: localhost
  run_once: true
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
  loop: "{{ terraform_templates }}"

- name: Generate files | Generate terraform pmx vm files
  delegate_to: localhost
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
  loop: "{{ terraform_multi_templates }}"

- name: Encrypt sensible data
  delegate_to: localhost
  run_once: true
  ansible.builtin.command: >
    ansible-vault encrypt "{{ terraform_project_path }}/terraform.tfvars"
  no_log: true
